### PR TITLE
Clean up codebase for style and consistency

### PR DESCRIPTION
**Pull request by nuudles**
This pull request cleans up the codebase by using the Android Studio "Reformat Code" tool. This tool fixes indentation and spacing issues to be consistent, optimizes imports, and reorders XML files for consistency. This tool also helps clean up the code to be consistent with Kotlin style guidelines and best practices.

This pull request also updates Kotlin and Gradle to the latest versions consistent with the latest version of Android Studio.

### CODE REVIEW

**Comment by Cliabhach** [comment]
@nuudles Would you like me to review these PRs?

**Comment by nuudles** [comment]
@Cliabhach I believe that @surreal8 will be merging in these PRs

**Comment by Cliabhach** [comment]
Understood. If I can do anything to help, let me know.

**Comment by nuudles** [comment]
Thanks @Cliabhach !

**Pull request merged**
